version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:23.4.0-browsers
    steps:
      - checkout
      - run:
          name: Check if PR is open
          command: |
            # Check if the current build was triggered by a PR
            if [ -z "${CIRCLE_PULL_REQUEST}" ]; then
              echo "This is not a PR, skipping job.";
              exit 0;  # Skip job if not a PR
            else
              echo "PR Detected: ${CIRCLE_PULL_REQUEST}";
            fi
      - run:
          name: Run Tests
          command: |
            echo "Running tests for PR..."

workflows:
  build_test:
    jobs:
      - test:
          filters:
            branches:
              only: main
              # ignore: /.*/  # Ignore all branches for this workflow, only PRs will trigger