version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18  # Use the CircleCI Node.js Docker image
    working_directory: ~/repo  # Set working directory to the root of the project
    steps:
      - checkout  # Checkout the code from your repository
      - run:
          name: Install dependencies
          command: npm install  # Install project dependencies
      - run:
          name: Run tests
          command: |
            npm test  # Run the tests using Jest

  check-pr:
    docker:
      - image: cimg/python:3.8  # A simple image for running script checks
    steps:
      - run:
          name: Check PR
          command: |
            if [ -z "$CIRCLE_PULL_REQUEST" ]; then
              echo "This is not a PR, skipping job.";
              exit 1;  # Fail if not a PR
            fi
            PR_BRANCH=$(echo $CIRCLE_PULL_REQUEST | sed 's#.*/\(.*\)/pull/\([0-9]*\)#\1#')
            if [ "$PR_BRANCH" != "Pull_Request_Test" ]; then
              echo "This PR is not targeting Pull_Request_Test, skipping job.";
              exit 1;  # Fail if PR is not targeting Pull_Request_Test
            fi
            echo "PR is targeting Pull_Request_Test, continuing the job."

workflows:
  version: 2
  build_test:
    jobs:
      - check-pr  # Ensure this job runs first to check if it's a PR targeting the correct branch
      - test:
          requires:
            - check-pr  # The test job will run only if the check-pr job passes
          filters:
            branches:
              only:
                - Pull_Request_Test  # Ensure the pipeline runs only for PRs targeting this branch
