version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:18  # Use the CircleCI Node.js Docker image
    working_directory: ~/repo  # Set working directory to the root of the project
    steps:
      - checkout  # Checkout the code from your repository
      - run:
          name: Install dependencies
          command: npm install  # Install project dependencies
      - run:
          name: Run tests
          command: |
            npm test  # Run the tests using Jest
            echo ${CIRCLE_BRANCH}

workflows:
  version: 2
  validate:
    jobs:
      - test:
          filters:
            branches:
              only:
                - Pull_Request_Test  # This ensures the pipeline runs only when a PR is created targeting this branch
