version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16  # Use an official Node.js Docker image (adjust version as needed)
    steps:
      - checkout  # Checkout the code from the PR
      - run:
          name: Install dependencies
          command: |
            npm install  # Install the Node.js project dependencies
      - run:
          name: Run tests
          command: |
            npm test  # Run tests (assuming you have a test script in package.json)
      - run:
          name: Verify PR source
          command: |
            # Check if this is a PR from a forked repository
            if [[ -n "$CIRCLE_PULL_REQUEST" && "$CIRCLE_PULL_REQUEST" == *"github.com"* ]]; then
              echo "PR is from a forked repository. Proceeding with the build."
            else
              echo "This PR is not from a forked repository. Skipping the build."
              exit 0  # Stop the build if it's not from a forked repository
            fi

workflows:
  version: 2
  pr-build:
    jobs:
      - build:
          filters:
            branches:
              - Pull_Request_Test
              - main